### ISSUE TITLE
Allow user to modify an existing event

### ISSUE THREAD

**Issue by JoeShep** [NSS-Day-Cohort-49/react-nutshell-jsxy-squad#7]
# Story

As a user, I should be able to modify an event that I previously created

# Acceptance Criteria

**Given** a user wants to modify an event that is not in the past
**When** the user is viewing their events
**Then** there should be an affordance that allows the user to modify the event

**Comment by joelbeckum** [comment]
-Add updateEvent to EventProvider module

-Add Edit affordance to EventCard module

-Refactor EventForm to edit event content

-Only edit future Events
