### ISSUE TITLE
Allow user to modify task name or date

### ISSUE THREAD

**Issue by JoeShep** [NSS-Day-Cohort-49/react-nutshell-jsxy-squad#8]
# Story

As a user, I should be able to modify a task that I previously created

# Acceptance Criteria

**Given** a user wants to modify a task that has not been marked complete
**When** the user is viewing their tasks
**Then** there should be an affordance that allows the user to modify the name and/or date of the task

**Comment by joelbeckum** [comment]
-Add updateTask to TaskProvider module

-Add Edit affordance to TaskCard module for all tasks where isComplete === false

-Refactor TaskForm to edit task content
